version: "3"
services:
  sqlserver:
    image: "microsoft/mssql-server-linux"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyComplexPassword!234
    expose:
      - "1443"
    ports:
      - "1443:1443"
  app:
    build:
      context: .
    ports:
      - "5000:80"