version: "3"
services:
  database:
    image: "microsoft/mssql-server-linux"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyComplexPassword!234
    expose:
      - "1433"
    ports:
      - "1433:1433"
  api:
    build:
      context: ./server
    restart: unless-stopped
  client:
    build:
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
        context: ./nginx
    ports:
        - '5000:80'