version: "3"
services:
  database:
    image: "microsoft/mssql-server-linux"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyComplexPassword!234
    expose:
      - "1433"
    ports:
      - "1433:1433"
  app:
    build:
      context: .
    ports:
      - "5000:80"